yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view
        (template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view
        (template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date', 'author',)

    def __str__(self):
        return self.text[:30]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Создание группы')
    slug = models.SlugField(unique=True, verbose_name='Параметр')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Заголовок'
        verbose_name_plural = 'Заголовки'

    def __str__(self):
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group',)
        labels = {'text': 'текст', 'group': 'группа'}
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView
# Create your views here.


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from .models import Group, Post, User
from .forms import PostForm
from .utils import get_page_context


def index(request):
    context = {
        'page_obj': get_page_context(request, Post.objects.all())
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': get_page_context(request, posts),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.select_related('group',
                                        ).filter(author__username=username)
    context = {
        'author': author,
        'page_obj': get_page_context(request, posts),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST, None)
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {'form': form, 'post_id': post_id}
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор данной странички</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. А 
  может и не напишу, времени совсем нет, чтобы писать.
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею. Нет, не умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static '/img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png'%}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main> 
      <div class="container py-5">
        {% block content %}
          Контента нет. Совсем нет.
        {% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
    </body>
  </html>

yatube/templates/includes/error_handling.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
      </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_cycle.html
{% load user_filters %}
{% for field in form %}
<div class="form-group row my-3"
  {% if field.field.required %} 
    aria-required="true"
  {% else %}
    aria-required="false"
  {% endif %}
>
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
    {% endif %}
  </div>
</div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}">Об авторе</a>
          </li>
        {% endwith %}
          <li class="nav-item">
            <a class="nav-link 
            {% if request.resolver_match.view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link
            {% if request.resolver_match.view_name  == 'posts:create' %}
              active
            {% endif %}"
            href="{% url 'posts:create' %}">Новая запись</a>
          </li>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light 
            {% if request.resolver_match.view_name  == 'users:password_change_form' %}
              active
            {% endif %}"
            href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light 
            {% if request.resolver_match.view_name  == 'users:logout' %}
              active
            {% endif %}"
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ post.author.get_full_name }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light"
            {% if request.resolver_match.view_name  == 'users:login' %}
              active
            {% endif %}
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
            {% if request.resolver_match.view_name  == 'users:signup' %}
              active
            {% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>      

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if form.instance.pk %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="navbar navbar-light" style="background-color: lightskyblue">
        {% if form.instance.pk %}Редактировать пост{% else %}Новый пост{% endif %}
      </div>
      {% load user_filters %}
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}
      {% include 'includes/error_handling.html' %}
        {% if form.instance.pk %}
          <form action="{% url 'posts:post_edit' post_id %}"
            method="post" enctype="multipart/form-data">
        {% else %}
          <form action="{% url 'posts:create' %}"
            method="post" enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}

        {% include 'users/login.html' %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">
            {% if form.instance.pk %}Сохранить изменения{% else %}Добавить новый пост{% endif %}
          </button>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaks }}</p>
    {% for post in posts %}
      <article>
        <br>Автор поста: {{ post.author.get_full_name }}
        <br>Дата публикации: {{ post.pub_date|date:"d E Y" }}
        <p>{{ post.text|linebreaks }}</p>
        <a class="btn btn-primary" href="{% url 'posts:profile' post.author %}">
          Все поcты пользователя
        </a>
        <a class="btn btn-primary" href="{% url 'posts:post_detail' post.id %}">
          Подробная информация
        </a>
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ 'Это главная страница этого замечательного сайта!' }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <p>Это главная страница этого замечательного сайта!</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text|linebreaks }}</p>
        {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        <br>
        <br>
        <a href="{% url 'posts:post_detail' post.id %}">
          подробная информация
        </a>
      </article>
      {% if not forloop.last %}<hr>{% endif %} 
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|slice:":30" }}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>   
            <li class="list-group-item">
              Группа: {{ post.group }}
            {% if user_post.group %}
              <a href="{% url 'posts:group_list' user_post.group.slug %}">все записи группы</a>
            {% endif %}
              </a>
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaksbr }}
          </p>
            {% if post.author == request.user %}
              <a href="{% url 'posts:post_edit' post.id %}">Редактировать
                запись</a>
            {% endif %}
          
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}       
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3> 
  {% for post in page_obj %}  
    <article>
      <ul>
        <li>
          Автор: {{ author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
      </ul>
        <p>
          {{ post.text|linebreaks }}
        </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      <br>
      {% if post.group %}       
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </article>
  {% endfor %}        
  {% include 'posts/includes/paginator.html' %}   
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/error_handling.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% include 'includes/form_cycle.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'password_reset' %}" class="btn btn-primary">
              Забыл(а) пароль? Вспоминай!
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
{%extends "base.html"%}
{%block title%}Пароль изменен успешно{%endblock%}
{%block content%}
{%load user_filters%}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{%endblock%}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/lpassword_reset_confirm.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
  </body>
</html>
{% endblock %}